spring:
  application:
    name: gatewayserver
#   config:
#     import:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 2000s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"
  data:
    redis:
      connect-timeout: 2s
      host: "localhost"
      port: 6379
      timeout: 1s

logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true


info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"


# CONFIGSERVER
server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"


resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 100000
        # automaticTransitionFromOpenToHalfOpenEnabled: true
        # eventConsumerBufferSize: 10
        # recordExceptions:
        #   - java.io.IOException
        #   - java.util.concurrent.TimeoutException
        # ignoreExceptions:
        #   - java.lang.RuntimeException 